#!/usr/bin/env ruby
# frozen_string_literal: true

# Uncomment this if you want to change the locale
# require 'oxaiworkers/load_i18n'
# I18n.default_locale = :ru

# Required external gems
require 'ox-ai-workers'
require 'irb'

# ### Start your code here ###

# Required my libs
require_relative 'my_assistant'

puts "OxAiWorkers #{OxAiWorkers::VERSION}"

# Configure
OxAiWorkers.configure do |config|
  config.access_token = ENV.fetch('OPENAI')
  config.model = 'gpt-4o-mini'
end

# Main algorithm
@assistant = MyAssistant.new
@assistant.task = '2 + 2 is ?'

IRB.start(__FILE__)
