#!/usr/bin/env ruby
# frozen_string_literal: true

require 'i18n'
I18n.load_path += Dir["#{File.expand_path('.oxaiworkers-local/locales')}/*.yml"]
I18n.default_locale = :en

# ### Start your code here

# Required external gems
require 'ox-ai-workers'
require 'irb'

# Required my libs
require_relative 'my_assistant'

puts "OxAiWorkers #{OxAiWorkers::VERSION}"

# Configure
OxAiWorkers.configure do |config|
  config.access_token = ENV.fetch('OPENAI')
  config.model = 'gpt-4o-mini'
end

# Main algorithm
@assistant = MyAssistant.new

IRB.start(__FILE__)
