#!/usr/bin/env ruby

require 'fileutils'

if ARGV.first == "init"
	dir = '.oxaiworkers-local'
	dest = "#{Dir.pwd}/#{dir}"
	source = File.expand_path('../../', __FILE__)

	unless Dir.exist? dir
		FileUtils.mkdir_p dir + "/locales"
		FileUtils.copy_entry source + "/locales", dest + "/locales"
		FileUtils.cp(source+"/exe/start", dest)
		puts "A #{dir} directory was created with the necessary initial settings."
		puts "Modify the settings as needed and run:"
		puts "#{dir}/start"
	else
		puts "Error: The #{dir} directory already exists."
	end
end