#!/usr/bin/env ruby

require 'fileutils'

if ARGV.first == "init"
	dir = '.oxaiworkers-local'
	dest = "#{Dir.pwd}/#{dir}"
	source = File.expand_path('../../', __FILE__)

	unless Dir.exist? dir
		FileUtils.mkdir_p dir + "/locales"
		FileUtils.copy_entry source + "/locales", dest + "/locales"
		FileUtils.cp(source+"/exe/start", dest)
		puts "#{dir} ...ok"
	else
		puts "#{dir} ...error (exists)"
	end
end