#!/usr/bin/env ruby
# frozen_string_literal: true

require 'fileutils'

puts 'Welcome to OxAiWorkers!'

if ARGV.first == 'init'
  dir = '.oxaiworkers-local'
  dest = "#{Dir.pwd}/#{dir}"
  source = File.expand_path('..', __dir__)

  if Dir.exist? dir
    puts "Error: The #{dir} directory already exists."
  else
    FileUtils.mkdir_p "#{dir}/locales"
    if ARGV.last == 'full'
      FileUtils.copy_entry "#{source}/template", dest.to_s
    else
      FileUtils.cp("#{source}/exe/start", dest)
    end
    puts "A #{dir} directory was created with the necessary initial settings."
    puts "Modify the settings as needed and run: #{dir}/start"
  end
end
