#!/usr/bin/env ruby
# frozen_string_literal: true

# Uncomment this if you want to change the locale
# require 'oxaiworkers/load_i18n'
# I18n.default_locale = :ru

# Start your code here
require 'ox-ai-workers'
require 'irb'

puts "OxAiWorkers #{OxAiWorkers::VERSION}"

OxAiWorkers.configure do |config|
  config.access_token = ENV.fetch('OPENAI')
  config.model = 'gpt-4o-mini'
end

@assistant = OxAiWorkers::Assistant::Sysop.new

IRB.start(__FILE__)
